### ISSUE TITLE
报错无法找到文件

### ISSUE THREAD

**Issue by lll666666** [rickzuo/xiaomi_video#2]
D:\Videos>python xiaomi.py D:\Videos\xiaomi_camera_videos\test --outdir D:\Videos\xiaomi_camera_videos
start merge:2023073100 video
data_dict: D:\Videos\xiaomi_camera_videos\test\2023073100 False
2023-08-06 13:03:47.190 | INFO     | __main__:merge_dirs:72 - 2023073100, 60 videos
Traceback (most recent call last):
  File "xiaomi.py", line 100, in <module>
    startup(args.indir, args.outdir)
  File "xiaomi.py", line 96, in startup
    merge_dirs(Path(date), outdir, date_name, "")
  File "xiaomi.py", line 87, in merge_dirs
    merge_vids(vidslist_path, Path(merge_outdir).joinpath(f"{ds_date}.mp4"))
  File "xiaomi.py", line 22, in merge_vids
    subprocess.run(cmd)
  File "D:\Program Files\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

请问这个是什么情况？

**Comment by rickzuo** [comment]
是不是没有安装ffmpeg

**Comment by lll666666** [comment]
> 是不是没有安装ffmpeg

是的，解决了
